name: Begin The Hunt!
description: Use when beginning a new bounty hunt
title: "\U0001F535 `<title-of-bounty-file>.md`"
body:
  - type: markdown
    attributes:
      value: |
        Please remember to mark **_and update_** the prefix of the title of this issue with one of the following emojis.
        1. 🔵&nbsp; Started working
        2. 🟢&nbsp; Ready for review
        3. 🟣&nbsp; Review completed

  - type: input
    id: bounty
    attributes:
      label: Link the bounty file
      description: Paste the link to the file for this bounty to help reviewers find the spec quickly
      placeholder: https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Description
      description: Provide any relevant details for your bounty which reviewers would find helpful or relevant
      value: |
        <!-- 
        Please remember to mark **_and update_** the prefix of the title of this issue with one of the following emojis.
        1. 🔵&nbsp; Started working
        2. 🟢&nbsp; Ready for review
        3. 🟣&nbsp; Review completed
        -->
    validations:
      required: false