name: Begin The Hunt! [test]
description: Use when beginning a new bounty hunt
title: "\U0001F535 `<title-of-bounty-file>.md`"
labels: []
assignees:
body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       This issue tracks progress on the bounty mentioned in the title.

  #       Please remember to mark and update your issue title with a prefix emoji of:
  #       1. 🔵&nbsp;: started working
  #       2. 🟢&nbsp;: ready for review
  #       3. 🟣&nbsp;: review completed
  - type: input
    id: bounty
    attributes:
      label: Link the bounty file
      description: Paste the link to the bounty file to help reviewers find the bounty spec quickly
      placeholder: https://github.com/tyvdh/stellar-quest-bounties/blob/main/bounties/level-1/create-bounties.md
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Description
      description: Provide any relevant details for your bounty which reviewers would find helpful or relevant
      placeholder: 
      value: 
    validations:
      required: false